Analise exploratoria dos dados

In [6]:
# importando Bibliotecas e o arquivo CSV
import pandas as pd
import plotly.express as px

car_data = pd.read_csv('../vehicles.csv')

In [7]:
car_data.head()

,price,model_year,model,condition,cylinders,fuel,odometer,transmission,type,paint_color,is_4wd,date_posted,days_listed
0,9400,2011.0,bmw x5,good,6.0,gas,145000.0,automatic,SUV,NaN,1.0,2018-06-23,19
1,25500,NaN,ford f-150,good,6.0,gas,88705.0,automatic,pickup,white,1.0,2018-10-19,50
2,5500,2013.0,hyundai sonata,like new,4.0,gas,110000.0,automatic,sedan,red,NaN,2019-02-07,79
3,1500,2003.0,ford f-150,fair,8.0,gas,NaN,automatic,pickup,NaN,NaN,2019-03-22,9
4,14900,2017.0,chrysler 200,excellent,4.0,gas,80903.0,automatic,sedan,black,NaN,2019-04-02,28

In [8]:
car_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 51525 entries, 0 to 51524
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   price         51525 non-null  int64
 1   model_year    47906 non-null  float64
 2   model         51525 non-null  str
 3   condition     51525 non-null  str
 4   cylinders     46265 non-null  float64
 5   fuel          51525 non-null  str
 6   odometer      43633 non-null  float64
 7   transmission  51525 non-null  str
 8   type          51525 non-null  str
 9   paint_color   42258 non-null  str
 10  is_4wd        25572 non-null  float64
 11  date_posted   51525 non-null  str
 12  days_listed   51525 non-null  int64
dtypes: float64(4), int64(2), str(7)
memory usage: 7.7 MB

In [9]:
car_data.describe()

,price,model_year,cylinders,odometer,is_4wd,days_listed
count,51525.000000,47906.000000,46265.000000,43633.000000,25572.0,51525.00000
mean,12132.464920,2009.750470,6.125235,115553.461738,1.0,39.55476
std,10040.803015,6.282065,1.660360,65094.611341,0.0,28.20427
min,1.000000,1908.000000,3.000000,0.000000,1.0,0.00000
25%,5000.000000,2006.000000,4.000000,70000.000000,1.0,19.00000
50%,9000.000000,2011.000000,6.000000,113000.000000,1.0,33.00000
75%,16839.000000,2014.000000,8.000000,155000.000000,1.0,53.00000
max,375000.000000,2019.000000,12.000000,990000.000000,1.0,271.00000

In [10]:
# Verificando valores ausentes
car_data.isnull().sum()

price               0
model_year       3619
model               0
condition           0
cylinders        5260
fuel                0
odometer         7892
transmission        0
type                0
paint_color      9267
is_4wd          25953
date_posted         0
days_listed         0
dtype: int64

In [16]:
# Correção de valores ausentes na coluna 'is_4wd'
car_data['is_4wd'] = car_data['is_4wd'].fillna(0)
car_data['is_4wd'].value_counts()

is_4wd
0.0    25953
1.0    25572
Name: count, dtype: int64

In [20]:
# Validando total da coluna 'is_4wd'
total_4wd = car_data['is_4wd'].count()
print(total_4wd)

51525

In [21]:
# Correção do tipo de dado da coluna 'date_posted'
car_data['date_posted'] = pd.to_datetime(car_data['date_posted'])

In [23]:
# Validando tipo de dado da coluna 'date_posted'
car_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 51525 entries, 0 to 51524
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   price         51525 non-null  int64
 1   model_year    47906 non-null  float64
 2   model         51525 non-null  str
 3   condition     51525 non-null  str
 4   cylinders     46265 non-null  float64
 5   fuel          51525 non-null  str
 6   odometer      43633 non-null  float64
 7   transmission  51525 non-null  str
 8   type          51525 non-null  str
 9   paint_color   42258 non-null  str
 10  is_4wd        51525 non-null  float64
 11  date_posted   51525 non-null  datetime64[us]
 12  days_listed   51525 non-null  int64
dtypes: datetime64[us](1), float64(4), int64(2), str(6)
memory usage: 7.2 MB

In [25]:
# correção de valores ausentes na coluna 'model_year'
car_data['model_year'] = car_data['model_year'].fillna(car_data.groupby('model')['model_year'].transform('median'))

In [29]:
# Validando o total da coluna 'model_year'
total_model_year = car_data['model_year'].count()
print(total_model_year)

car_data['model_year'].describe()

51525

count    51525.000000
mean      2009.793954
std          6.099296
min       1908.000000
25%       2007.000000
50%       2011.000000
75%       2014.000000
max       2019.000000
Name: model_year, dtype: float64

In [30]:
# correção de valores ausentes na coluna 'cylinders'
car_data['cylinders'] = car_data['cylinders'].fillna(car_data.groupby('model')['cylinders'].transform('median'))

In [31]:
# validando o total da coluna 'cylinders'
total_cylinders = car_data['cylinders'].count()
print(total_cylinders)

car_data['cylinders'].describe()

51525

count    51525.000000
mean         6.121067
std          1.657457
min          3.000000
25%          4.000000
50%          6.000000
75%          8.000000
max         12.000000
Name: cylinders, dtype: float64

In [32]:
# correção de valores ausentes na coluna 'paint_color'
car_data['paint_color'] = car_data['paint_color'].fillna('Unknown')

In [34]:
# validando o total da coluna 'paint_color'
total_paint_color = car_data['paint_color'].count()
print(total_paint_color)

car_data['paint_color'].describe()

51525

count     51525
unique       13
top       white
freq      10029
Name: paint_color, dtype: object

In [36]:
# correção de valores ausentes na coluna 'odometer'
car_data['vehicle_age'] = 2019 - car_data['model_year'] + 1

car_data['odometer'] = car_data['odometer'].fillna(car_data.groupby('vehicle_age')['odometer'].transform('median'))

In [37]:
# validando o total da coluna 'odometer'
total_odometer = car_data['odometer'].count()
print(total_odometer)

car_data['odometer'].describe()

51524

count     51524.000000
mean     115199.710252
std       62083.200279
min           0.000000
25%       73500.000000
50%      114074.000000
75%      152862.000000
max      990000.000000
Name: odometer, dtype: float64

In [ ]:
# Analise de valores outliers
car_data[['price', 'model_year', 'odometer', 'days_listed']].describe()

               price    model_year       odometer  days_listed
count   51525.000000  51525.000000   51524.000000  51525.00000
mean    12132.464920   2009.793954  115199.710252     39.55476
std     10040.803015      6.099296   62083.200279     28.20427
min         1.000000   1908.000000       0.000000      0.00000
25%      5000.000000   2007.000000   73500.000000     19.00000
50%      9000.000000   2011.000000  114074.000000     33.00000
75%     16839.000000   2014.000000  152862.000000     53.00000
max    375000.000000   2019.000000  990000.000000    271.00000

In [46]:
# Coluna 'price'
car_data.sort_values('price', ascending=False).head(10)

,price,model_year,model,condition,cylinders,fuel,odometer,transmission,type,paint_color,is_4wd,date_posted,days_listed,vehicle_age
12504,375000,1999.0,nissan frontier,good,6.0,gas,115000.0,automatic,pickup,blue,1.0,2018-05-19,21,21.0
11359,300000,2015.0,ram 2500,excellent,6.0,diesel,78285.5,automatic,truck,grey,1.0,2018-10-15,39,5.0
1309,189000,2014.0,ford f-150,good,6.0,gas,151248.0,automatic,truck,black,0.0,2019-03-02,56,6.0
27375,189000,2014.0,ford f-150,good,6.0,gas,151248.0,automatic,truck,black,0.0,2018-09-25,72,6.0
34389,189000,2014.0,ford f-150,good,6.0,gas,151248.0,automatic,truck,black,0.0,2019-02-02,28,6.0
30634,189000,2014.0,ford f-150,good,6.0,gas,90000.0,automatic,truck,black,0.0,2018-07-21,42,6.0
1668,189000,2014.0,ford f-150,good,6.0,gas,151248.0,automatic,truck,Unknown,0.0,2019-03-20,21,6.0
33434,189000,2014.0,ford f-150,good,6.0,gas,151248.0,automatic,truck,black,0.0,2019-02-05,102,6.0
34206,175000,2004.0,gmc sierra 2500hd,good,8.0,diesel,149000.0,automatic,truck,grey,1.0,2018-08-25,57,16.0
41748,145000,2008.0,toyota tundra,like new,8.0,gas,140000.0,automatic,truck,red,1.0,2018-06-16,29,12.0

In [ ]:
# removendo a linha de indice 12504, Modelo muito antigo com o maior preço, provavelmente um erro de digitação e puxando a media para cima
car_data = car_data.drop(index=12504)

In [50]:
# validando coluna 'price'
car_data.sort_values('price', ascending=False).head(3)

,price,model_year,model,condition,cylinders,fuel,odometer,transmission,type,paint_color,is_4wd,date_posted,days_listed,vehicle_age
11359,300000,2015.0,ram 2500,excellent,6.0,diesel,78285.5,automatic,truck,grey,1.0,2018-10-15,39,5.0
27375,189000,2014.0,ford f-150,good,6.0,gas,151248.0,automatic,truck,black,0.0,2018-09-25,72,6.0
1309,189000,2014.0,ford f-150,good,6.0,gas,151248.0,automatic,truck,black,0.0,2019-03-02,56,6.0

In [ ]:
# coluna 'odometer'
car_data.sort_values('odometer', ascending=False).head(10)

,price,model_year,model,condition,cylinders,fuel,odometer,transmission,type,paint_color,is_4wd,date_posted,days_listed,vehicle_age
17869,59900,1964.0,chevrolet corvette,like new,8.0,gas,990000.0,automatic,convertible,red,0.0,2018-06-17,28,56.0
40729,4700,2013.0,chevrolet cruze,good,6.0,gas,990000.0,automatic,sedan,black,0.0,2018-05-02,4,7.0
48962,40000,2014.0,ram 3500,excellent,6.0,diesel,980000.0,automatic,truck,white,1.0,2018-12-06,7,6.0
14245,6000,1996.0,ram 2500,good,10.0,gas,920000.0,automatic,truck,blue,0.0,2019-02-02,43,24.0
2840,18500,2014.0,ford explorer,excellent,6.0,gas,866000.0,automatic,SUV,black,1.0,2018-07-20,14,6.0
2440,5300,2010.0,toyota corolla,excellent,4.0,gas,840000.0,automatic,sedan,silver,0.0,2019-02-04,13,10.0
32973,5550,2010.0,toyota corolla,excellent,4.0,gas,840000.0,automatic,sedan,silver,0.0,2018-10-21,20,10.0
13027,8500,2015.0,chevrolet malibu,excellent,4.0,gas,838095.0,automatic,sedan,silver,0.0,2018-05-30,10,5.0
41699,10300,2013.0,ford escape,excellent,6.0,gas,831000.0,automatic,SUV,brown,0.0,2018-05-27,30,7.0
5735,7500,2015.0,hyundai elantra,excellent,4.0,gas,813542.0,other,coupe,brown,0.0,2018-11-21,5,5.0

In [52]:
# coluna 'model_year'
car_data.sort_values('model_year').head(10)

,price,model_year,model,condition,cylinders,fuel,odometer,transmission,type,paint_color,is_4wd,date_posted,days_listed,vehicle_age
33906,12995,1908.0,gmc yukon,good,8.0,gas,169328.0,automatic,SUV,black,0.0,2018-07-06,34,112.0
33907,12995,1908.0,cadillac escalade,excellent,8.0,gas,169328.0,automatic,SUV,white,0.0,2018-06-24,25,112.0
45694,18000,1929.0,ford f-150,good,8.0,gas,NaN,manual,other,silver,0.0,2018-11-18,59,91.0
34713,5000,1936.0,ford f-150,excellent,6.0,gas,30000.0,manual,pickup,purple,0.0,2018-11-22,10,84.0
22595,21000,1948.0,chevrolet impala,like new,8.0,gas,4000.0,automatic,sedan,red,0.0,2019-01-18,24,72.0
36582,44900,1949.0,chevrolet suburban,good,8.0,gas,1800.0,automatic,wagon,orange,0.0,2018-08-19,10,71.0
14752,15000,1954.0,ford f-150,excellent,8.0,gas,3565.0,manual,pickup,black,0.0,2019-02-16,13,66.0
10018,23900,1955.0,ford f250,excellent,6.0,gas,47180.0,manual,truck,blue,0.0,2018-12-22,61,65.0
39580,35000,1958.0,chevrolet impala,excellent,8.0,gas,3184.0,automatic,coupe,black,0.0,2018-05-19,33,62.0
48414,37900,1958.0,chevrolet impala,good,8.0,gas,62799.0,automatic,coupe,Unknown,0.0,2018-08-11,10,62.0

In [53]:
# coluna 'days_listed'
car_data.sort_values('days_listed', ascending=False).head(10)

,price,model_year,model,condition,cylinders,fuel,odometer,transmission,type,paint_color,is_4wd,date_posted,days_listed,vehicle_age
4360,5200,2011.0,chevrolet impala,like new,6.0,gas,122000.0,automatic,sedan,Unknown,0.0,2018-05-24,271,9.0
28756,5500,2011.0,nissan versa,excellent,4.0,gas,96000.0,automatic,hatchback,blue,0.0,2019-01-08,267,9.0
2224,5995,2004.0,ford f-250,good,8.0,gas,103000.0,automatic,truck,red,1.0,2019-01-24,263,16.0
51,3800,2012.0,ford focus,good,4.0,gas,130323.0,automatic,sedan,black,0.0,2018-11-29,261,8.0
7875,8980,2013.0,nissan altima,excellent,6.0,gas,101611.0,automatic,coupe,blue,0.0,2019-02-02,256,7.0
46583,11500,2017.0,ford fusion,excellent,4.0,gas,65000.0,automatic,sedan,red,0.0,2019-03-06,252,3.0
3202,5995,2009.0,toyota prius,excellent,4.0,gas,130000.0,automatic,hatchback,blue,0.0,2018-10-17,244,11.0
24527,5995,2007.0,toyota rav4,good,4.0,gas,106000.0,automatic,SUV,custom,1.0,2018-06-29,243,13.0
19763,31995,2015.0,jeep wrangler unlimited,excellent,6.0,gas,78285.5,automatic,wagon,Unknown,1.0,2018-11-16,240,5.0
11698,21995,2019.0,chevrolet impala,like new,6.0,gas,14151.5,automatic,sedan,black,0.0,2019-02-24,236,1.0

In [62]:
# Analise de valores outliers quantis
desc = car_data['price'].describe()

limites = [desc['min'], desc['25%'], desc['50%'], desc['75%'], desc['max']]

faixas = pd.cut(car_data['price'], bins=limites, include_lowest=True)

print(faixas.value_counts().sort_index())

price
(0.999, 5000.0]        13233
(5000.0, 9000.0]       12651
(9000.0, 16836.0]      12759
(16836.0, 300000.0]    12881
Name: count, dtype: int64